tap "gromgit/fuse"
tap "homebrew/bundle"
tap "homebrew/services"
tap "ngrok/ngrok"
tap "twilio/brew"
# General-purpose data compression with high compression ratio
brew "xz"
# OpenType text shaping engine
brew "harfbuzz"
# Image format providing lossless and lossy compression for web images
brew "webp"
# YAML Parser
brew "libyaml"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Library for command-line editing
brew "readline"
# Official Amazon AWS command-line interface
brew "awscli"
# Parser generator
brew "bison"
# Cross-platform make
brew "cmake"
# Tool for managing dock items
brew "dockutil"
# Command-line tool for DigitalOcean
brew "doctl"
# CLI for FastAPI framework
brew "fastapi"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl2"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fast and simple Node.js version manager
brew "fnm"
# GNU database manager
brew "gdbm"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Portable Foreign Function Interface library
brew "libffi"
# Library for USB device access
brew "libusb"
# List USB devices, just like the Linux lsusb command
brew "lsusb"
# Mac App Store command-line interface
brew "mas"
# Create BitTorrent metainfo files
brew "mktorrent"
# Media player based on MPlayer and mplayer2
brew "mpv"
# SMTP client that can be used as an SMTP plugin for Mutt
brew "msmtp"
# General-purpose lossless data-compression library
brew "zlib"
# Open source relational database management system
brew "mysql"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Graphical client for the Soulseek peer-to-peer network
brew "nicotine-plus"
# Small build system for use with gyp or CMake
brew "ninja"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Package for scientific computing with Python
brew "numpy"
# Core utilities for Python packages
brew "python-packaging"
# Open source computer vision library
brew "opencv"
# Open source suite of directory software
brew "openldap"
# Information gathering framework for phone numbers
brew "phoneinfoga"
# General-purpose scripting language
brew "php"
# Object-relational database system
brew "postgresql@14", restart_service: :changed
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# It's not just a linter that annoys you!
brew "pylint"
# Tool Command Language
brew "tcl-tk"
# Python interface to Tcl/Tk
brew "python-tk@3.12"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Software environment for statistical computing
brew "r"
# Ruby version manager
brew "rbenv"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Safe, concurrent, practical language
brew "rust"
# Library for loading images as SDL surfaces and textures
brew "sdl2_image"
# Library for using TrueType fonts in SDL applications
brew "sdl2_ttf"
# Hunt down social media accounts by username
brew "sherlock"
# Change macOS audio source from the command-line
brew "switchaudio-osx"
# Open source continuous file synchronization application
brew "syncthing", restart_service: :changed
# User interface to the TELNET protocol
brew "telnet"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Internet file retriever
brew "wget"
# Utilities to create and convert Web Open Font File (WOFF) files
brew "woff2"
# UNIX shell (command interpreter)
brew "zsh"
# File system client based on SSH File Transfer Protocol
brew "gromgit/fuse/sshfs-mac"
# unleash the power of Twilio from your command prompt
brew "twilio/brew/twilio"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Application launcher and productivity software
cask "alfred"
# Records audio from any application
cask "audio-hijack"
# Integrated CAD, CAM, CAE, and PCB software
cask "autodesk-fusion"
# Data backup and storage service
cask "backblaze"
# Virtual Audio Driver
cask "blackhole-2ch"
# Shoutcast and Icecast streaming client
cask "butt"
# Communication with Canon EOS cameras
cask "canon-eos-utility"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Server and cloud storage browser
cask "cyberduck"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Downloads videos from different websites
cask "downie"
# Web browser
cask "firefox"
# Open-source platform for visualizing and manipulating large graphs
cask "gephi"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# Open-source video transcoder
cask "handbrake"
# Automated organisation
cask "hazel"
# Free and open-source media player
cask "iina"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Manage your Google Drive and OneDrive files
cask "insync"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Enable generative AI features in iTerm2
cask "itermai"
# File archiver
cask "keka"
# Software for Logitech devices
cask "logi-options+"
# File system integration
cask "macfuse"
# Media key forwarder for iTunes and Spotify
cask "macmediakeyforwarder"
# Sandbox construction video game
cask "minecraft"
# Audio mixer controller
cask "mixing-station"
# Open-source DJ software
cask "mixxx"
# Music tagger
cask "musicbrainz-picard"
# Multi-agent programmable modelling environment
cask "netlogo"
# Open-source software for live streaming and screen recording
cask "obs"
# Client for Proton Mail and Proton Calendar
cask "proton-mail"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "proton-mail-bridge"
# VPN client focusing on security
cask "protonvpn"
# G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.)
cask "prusaslicer"
# Control DMX or analogue lighting systems
cask "qlc+"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Quick Look plugin for CSV files
cask "quicklook-csv"
# Quick Look plugin for JSON files
cask "quicklook-json"
# Internet radio player for the menu bar
cask "radiola"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin"
# Unpacks archive files
cask "the-unarchiver"
# Open-source BitTorrent client
cask "transmission"
cask "transmission-remote-gui"
# Easy to use text extraction tool
cask "trex"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Quick Look plugin for webp files
cask "webpquicklook"
# Agentic IDE powered by AI Flow paradigm
cask "windsurf"
# Remote control for Behringer X32 audio consoles
cask "x32-edit"
# Lossless audio decoder
cask "xld"
vscode "ahmadalli.vscode-nginx-conf"
vscode "astro-build.astro-vscode"
vscode "bmewburn.vscode-intelephense-client"
vscode "christian-kohler.npm-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "ibm.output-colorizer"
vscode "inferrinizzard.prettier-sql-vscode"
vscode "jebbs.plantuml"
vscode "jinhyuk.replace-curly-quotes"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.mypy-type-checker"
vscode "ms-python.pylint"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "oracle.oracle-java"
vscode "philipp-burckhardt.llm-context-builder"
vscode "raynigon.nginx-formatter"
vscode "redhat.java"
vscode "techer.open-in-browser"
vscode "tomoki1207.pdf"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vue.volar"
vscode "william-voyek.vscode-nginx"
vscode "yzhang.markdown-all-in-one"
